apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-BUILDNO
  labels:
    app: roboshop
    tier: mysql
    build: "BUILDNO"
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: mysql
      build: "BUILDNO"
  template:
    metadata:
      labels:
        tier: mysql
        build: "BUILDNO"
    spec:
      containers:
        - name: frontend
          image: rkalluru/b48-mysql:BUILDNO
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: mysql-cred
